/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2024
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003 
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cy_pdl.h"
#include "cybsp.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define MY_TCPWM_CNT_MULT_MASK  (uint32_t)(ASTIMER_MASK)  /* |\ */
                                              /* (1UL << MY_TCPWM_CNT_5) |\ */
                                              /* (1UL << MY_TCPWM_CNT_6))   */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
cy_stc_sysint_t timer_intr_cfg =
{
    .intrSrc = ASTIMER_IRQ,  /* Source of interrupt signal*/
    .intrPriority = 3UL    /* Interrupt priority */
};

/**********************************************************************************************************************
 * Function Name: timer_isr_handler
 * Summary:
 *   TIMER interrupt service routine.
 *   Although interrupt is called by CC and TC, CC will be skiped according to intStatus..
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
void Timer_Handler(void)
{
    uint32_t intStatus = Cy_TCPWM_GetInterruptStatusMasked(ASTIMER_HW, ASTIMER_NUM);
    Cy_TCPWM_ClearInterrupt(ASTIMER_HW, ASTIMER_NUM, intStatus);

    if ((intStatus & CY_TCPWM_INT_ON_TC ) != 0UL)
    {
        Cy_GPIO_Inv(CYBSP_USER_LED1_PORT, CYBSP_USER_LED1_PIN);
    }
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 *   1. Initializes the BSP.
 *   2. Configures the interrupt.
 *   3. Configures the timer and counter peripherals.
 *   4. Trigger the Timer block.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;
    /* Initialize the device and board peripherals */
    result = cybsp_init() ;
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize TIMER interrupt */
    result = Cy_SysInt_Init(&timer_intr_cfg, Timer_Handler);
    if(result != CY_SYSINT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    /* Clearing and enabling the Timer interrupt in NVIC */
    NVIC_ClearPendingIRQ(timer_intr_cfg.intrSrc);
    NVIC_EnableIRQ(timer_intr_cfg.intrSrc);

    /* Initialize the TIMER */
    if (CY_TCPWM_SUCCESS != Cy_TCPWM_Counter_Init(ASTIMER_HW, ASTIMER_NUM, &ASTIMER_config))
    {
        /* Handle possible errors */
        CY_ASSERT(0);
    }
    /* Enables the counter and TriggerStart*/
    Cy_TCPWM_Counter_Enable(ASTIMER_HW, ASTIMER_NUM);
    Cy_TCPWM_TriggerStart(ASTIMER_HW, MY_TCPWM_CNT_MULT_MASK);

    for (;;)
    {
    }
}

/* [] END OF FILE */
